### ISSUE TITLE
prompt component return false, url changed

### ISSUE THREAD

**Issue by wklc2014** [ZacharyRSmith/react-router-navigation-prompt#60] opened 2020-01-03 11:29 UTC
Hi, when I use this component, If I refrush the browser, and then click this back button of browser, the  confirm modal will show, and the url is changed too, then if I click cancel, the page is not change.

so, the url is not right with the render page.

Is there anyone appeared it ?

any more, even if I use Prompt component of react-router, It had the same problerm.

how resolve the problerm?

**Comment by ZacharyRSmith** [comment] 2020-01-04 13:02
Thanks for reporting this!  Closing because this is a duplicate of #37

**Closed by ZacharyRSmith** 2020-01-04 13:02 UTC
Labels: duplicate
