### ISSUE TITLE
Can I close the pop-up window when I refresh the browser or keep it consistent with the logic style of the custom page when I leave the page

### ISSUE THREAD

**Issue by liuxiansheng2018** [ZacharyRSmith/react-router-navigation-prompt#72] opened 2021-02-01 05:48 UTC
![image](https://user-images.githubusercontent.com/35281468/106419721-0498eb00-6494-11eb-8c78-cbf229c28850.png)
![image](https://user-images.githubusercontent.com/35281468/106419739-124e7080-6494-11eb-9dc9-e4310d19c22e.png)

**Comment by ZacharyRSmith** [comment] 2021-02-02 23:34
Closing because this is a duplicate of https://github.com/ZacharyRSmith/react-router-navigation-prompt/issues/71

**Closed by ZacharyRSmith** 2021-02-02 23:34 UTC
