### ISSUE TITLE
Prompt doesn't show when I'm using with Gatsby

### ISSUE THREAD

**Issue by ningo-agilityio** [ZacharyRSmith/react-router-navigation-prompt#62] opened 2020-02-23 14:41 UTC
I'm using `"gatsby": "^2.17.7"` and I had some pages:
- /membership
- /create-account?step=1
- /create-account?step=2

This is my code for Prompt
```
<NavigationPrompt when={true}>
        {({ onConfirm, onCancel }) =>
          true && (
            <Modal
              handleDismiss={onCancel}
              classNames={{
                content: `w-fit-content w-moz-fit-content md:h-fit-content`,
              }}
            >
              <div
                className={`md:my-30 md:mx-60 my-10 mx-0`}
              >
                Confirmation
              </div>
            </Modal>
          )
        }
      </NavigationPrompt>
```

I'm expecting to show Prompt when hit back between these pages, but it only shows when I reload `/create-account` page. Are there any official issue for this?
I got stuck with this for 2 weeks. 
Please help to give you your advice if any. Thanks a lot.

**Comment by ZacharyRSmith** [comment] 2020-02-25 01:30
Hi @ningo-agilityio , thanks for opening the first issue referencing gatsby!

Would you please provide a full event flow example for "when hit back between these pages"?  Ie, which page do you start on, what do you do until the unexpected behavior?

**Comment by ningo-agilityio** [comment] 2020-02-25 02:39
Hi @ZacharyRSmith.
Thanks for your response.

My steps will go through:
1. /membership
2. /create-account?step=1
3. /create-account?step=2
4. /create-account?step=3
I did use `NavigationPrompt` inside `CreateAccount` component to expect a prompt will be showed when user hits back in any step. But:
- From /create-account to /membership, no popup was showed (even default browser)
- Within /create-account steps, only default browser popup was showed, my expectation is showing my customize popup.
![Screen Shot 2020-02-25 at 9 38 32 AM](https://user-images.githubusercontent.com/9548275/75210059-a5762500-57b2-11ea-98e7-383850740215.png)

**Comment by ZacharyRSmith** [comment] 2020-03-27 20:36
@ningo-agilityio , my apologies for my delayed response.

Re: /create-account steps -- It looks like you are reloading the site, and for security concerns browsers usually handle this navigation UX themselves, leading to vanilla alert boxes.

Re: going from /create-account back to /membership -- I'm not sure what is going on here.  I would like to see more code, but I understand if you cannot share that code.

As is, I don't think this is a bug with NavigationPrompt, so I will close this issue.  If you are able to provide more details, please reopen the issue with those details.  Thanks!

**Closed by ZacharyRSmith** 2020-03-27 20:36 UTC
