### ISSUE TITLE
History is blocked when you navigate away

### ISSUE THREAD

**Issue by smiket** [ZacharyRSmith/react-router-navigation-prompt#3] opened 2017-12-03 16:06 UTC
https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/5a6a6fe433d496bf2d1ea80e81a9896c7ca80cec/src/index.js#L90

Hi Zachory - I noticed an issue when navigating away from the current page.
I first prompt and select no (do not navigate away).
I then prompt and select yes (navigate away).
The app opens the next page, but then history remains blocked (navigation stops working.
I believe its from the line I highlight above - let me know if I'm missing something.

Thanks for a very nice component!

**Comment by ZacharyRSmith** [comment] 2017-12-04 14:23
Thanks for the compliment!

Yes, that line is re-blocking history so that `<NavigationPrompt/>` can continue blocking history if desired -- ie, if 1) `<NavigationPrompt/>` is still mounted and 2) its props.when is true or returns true.  Why is it continuing to block when you do not want it to, I do not know.

When you say "history remains blocked", are you seeing prompts when you try to navigate?

If so, update props.when to be false or return false.

If not, then maybe componentWillUnmount() is not successfully unblocking history?

I'd be interested in seeing more code if you can share.

**Comment by smiket** [comment] 2017-12-06 15:31
Hi Zach, in my case the history remained blocked because I left the page.  When you confirm the navigation, the last thing that happens is that call to set state (blocking history).  On my other page, I don't have the NavigationPrompt so no unblocking occurs there - and then none of my links work (nav is blocked).

I ended up taking your code and just supporting 'didCancel' and 'didConfirm so that I could always unblock when unmounting the component.  Here's what I ended up with (your code without the AfterCancel/AfterConfirm).

```
class NavigationPrompt extends React.Component {
    /**
     * Default constructor.
     * @param {any} props - set by parent component (via JSX markup).
     */
    constructor(props) {
        super(props);

        this.state = {
            ...initState,
            unblock: props.history.block(this.block)
        };
    }

    /*
     * Property types for the current component.
     */
    static propTypes = {
        /** 
         * Function to be called when cancel occurs.
         */
        didCancel: PropTypes.func,
        /**
         * Function to be called when confirm occurs.
         */
        didConfirm: PropTypes.func,
        /**
         * Called to obtain child element - children(bool isActive, Func onCancel, Func onConfirm) -> JSX.Element
         */
        children: PropTypes.func.isRequired
    }

    /*
     * Default property values for current component.    
     */
    static defaultProps = {
        didCancel: () => { },
        didConfirm: () => { }
    }

    /**
     * React lifecycle method (component has been mounted to real DOM).
     * @returns {undefined}
     */
    componentDidMount() {
        window.addEventListener('beforeunload', this.onBeforeUnload);
    }

    /**
     * React lifecycle method (component will be removed from the real DOM).
     * @returns {undefined}
     */
    componentWillUnmount() {
        this.state.unblock();
        window.removeEventListener('beforeunload', this.onBeforeUnload);
    }

    /**
     * Window unload handler.
     * @param {any} e the window unload event object.
     * @returns {string} message for the native browser window,
     */
    onBeforeUnload = (e) => {
        if (!this.when()) {
            return;
        }

        const msg = 'Do you want to leave this site?\n\nChanges you made may not be saved.';
        e.returnValue = msg;
        return msg;
    }

    /**
     * Cancel handler.
     * @returns {undefined}
     */
    onCancel = () => {
        this.props.didCancel();
        this.setState({ ...initState });
    }

    /**
     * Confirm handler.
     * @returns {undefined}
     */
    onConfirm = () => {
        this.props.didConfirm();
        this.navigateToNextLocation();
    }

    /**
     * Navigate to next location.
     * @returns {undefined}
     */
    navigateToNextLocation = () => {
        let { action, nextLocation } = this.state;
        action = {
            POP: 'push',
            PUSH: 'push',
            REPLACE: 'replace'
        }[action || 'PUSH'];

        if (!nextLocation) {
            nextLocation = { pathname: '/' };
        }

        this.state.unblock();
        this.props.history[action](nextLocation.pathname);
    }

    /**
     * Determines when component should be evaluating navigability / blockage.
     * @param {any} nextLocation the next location.
     * @returns {boolean} evaluation should occur.
     */
    when = (nextLocation) => {
        if (typeof this.props.when === 'function') {
            return this.props.when(this.props.location, nextLocation);
        }
        return this.props.when;
    }

    /**
     * Determine whether to block navigation to the next location.
     * @param {any} nextLocation the next location.
     * @param {any} action to evaluate navigability.
     * @returns {boolean} whether to allow navigation or not.
     */
    block = (nextLocation, action) => {
        if (this.when(nextLocation)) {
            this.setState({
                action,
                nextLocation,
                isActive: true
            });
        }
        return !this.when(nextLocation);
    }

    /**
     * React lifecycle method, called whenever state or property change occurs.
     * @returns {JSX.Element} a react element.
     */
    render() {
        if (!this.state.isActive && !this.props.renderIfNotActive) {
            return null;
        }

        return (
            <div>
                { this.props.children(this.state.isActive, this.onConfirm, this.onCancel) }
            </div>
        );
    }
}
```

**Comment by ZacharyRSmith** [comment] 2017-12-06 21:58
Yes, the last thing that happens is that call to set state, blocking history...but in my experience if the other page does not have NavigationPrompt, then history is not blocked (I presume because componentWillUnmount() calls this.state.unblock()). I would love it if you would share some code that reproduces what you're seeing.

**Comment by smiket** [comment] 2017-12-07 20:22
I'll see if I can nail down the issue, perhaps make a small POC for illustration.  I'm using React 16 if that is of any consequence.

**Comment by ZacharyRSmith** [comment] 2017-12-07 22:30
Thanks, I appreciate it @smiket !

**Comment by ZacharyRSmith** [comment] 2018-01-20 03:17
Closing due to being unable to reproduce.

**Closed by ZacharyRSmith** 2018-01-20 03:17 UTC

**Comment by ZacharyRSmith** [comment] 2018-01-21 06:44
auto tests for this issue in #12
